// <auto-generated />
using System;
using Code_Academy_Space_Booking_System_project.MyDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Code_Academy_Space_Booking_System_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231219211845_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Bill", b =>
                {
                    b.Property<int>("Bill_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bill_Id"), 1L, 1);

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool>("Payment_Status")
                        .HasColumnType("bit");

                    b.HasKey("Bill_Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Booking", b =>
                {
                    b.Property<int>("Book_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Book_ID"), 1L, 1);

                    b.Property<int?>("BillID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateTime>("End_Day")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start_Day")
                        .HasColumnType("datetime2");

                    b.HasKey("Book_ID");

                    b.HasIndex("BillID");

                    b.HasIndex("CustomerID");

                    b.ToTable("Book");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Customer", b =>
                {
                    b.Property<int>("Customer_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Customer_ID"), 1L, 1);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("DoB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<long>("House_Num")
                        .HasColumnType("bigint");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customer_ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Space", b =>
                {
                    b.Property<int>("Space_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Space_ID"), 1L, 1);

                    b.Property<int?>("BookID")
                        .HasColumnType("int");

                    b.Property<int>("BooksBook_ID")
                        .HasColumnType("int");

                    b.Property<string>("Building_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Hight")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Space_Status")
                        .HasColumnType("bit");

                    b.Property<double>("Width")
                        .HasColumnType("float");

                    b.HasKey("Space_ID");

                    b.HasIndex("BooksBook_ID");

                    b.ToTable("Spaces");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Bill", b =>
                {
                    b.HasOne("Code_Academy_Space_Booking_System_project.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Booking", b =>
                {
                    b.HasOne("Code_Academy_Space_Booking_System_project.Model.Bill", "Bills")
                        .WithMany()
                        .HasForeignKey("BillID");

                    b.HasOne("Code_Academy_Space_Booking_System_project.Model.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerID");

                    b.Navigation("Bills");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Code_Academy_Space_Booking_System_project.Model.Space", b =>
                {
                    b.HasOne("Code_Academy_Space_Booking_System_project.Model.Booking", "Books")
                        .WithMany()
                        .HasForeignKey("BooksBook_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
